correccion de renderItems y tests de select  y label
Laboratoria/impl-dev-data-lovers pull request #25
Opened 2023-08-23 00:07 UTC by DeysiVergara

2023-08-23 00:12 UTC, unjust commented
@DeysiVergara ya cambie renderItems en otro rama aparte, solo este cambio. Puedes dedicar esta rama a los tests:oas-html.

2023-08-24 21:52 UTC, unjust approved these changes
Me parece bien el codigo - solo que por algun razon tienes cambios de renderItems que ya existen en la implementacion.

2023-08-25 06:30 UTC, merunga commented on tests-read-only/oa/oa-html.spec.js
>      });
agruparia todo lo q tiene q ver con `select` en su propio `describe` anidado

2023-08-25 06:30 UTC, merunga commented on tests-read-only/oa/oa-css.spec.js
> +document.querySelector('#root').innerHTML = renderItems(fakeData);
nos se si lo ataca otro PR, pero aca necesitamos la misma funcion q en los oas de css, para renderizar condicionalmente según el tipo de dato del resultado
@unjust

2023-08-25 06:30 UTC, merunga commented on tests-read-only/oa/oa-html.spec.js
> +      expect(lis.length).toBeGreaterThan(0);
esto no es redundante con lo q esta en la linea 96?

2023-08-25 16:37 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +      expect(lis.length).toBeGreaterThan(0);
quiza una forma afuera podemos hacer
```
 expect(lis[0].getAttribute('itemtype')).not.toBeNull();
expect(lis[0].getAttribute('itemscope')).not.toBeNull();
```
y esta va a tirar un error que no es definido

2023-08-25 16:38 UTC, merunga commented on tests-read-only/oa/oa-html.spec.js
> +      expect(lis.length).toBeGreaterThan(0);
y esto? https://jestjs.io/docs/expect#expecthasassertions

2023-08-25 16:40 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +      expect(lis.length).toBeGreaterThan(0);
No recordaba eso. SI probamos aqui y donde hemos hecho repeticiones en otra partes @DeysiVergara

2023-08-25 17:01 UTC, unjust requested changes
intentamos con los assertions y otro feedback de merunga

2023-08-25 20:16 UTC, merged