Cambios readme fbalexis
Laboratoria/impl-dev-data-lovers pull request #29
Opened 2023-08-24 22:32 UTC by DeysiVergara

2023-08-24 23:58 UTC, unjust reviewed
Algunas sugerencias.

Creo podemos poner el parte de 
```
Se podría  agregar la sección de pruebas o al menos esta parte para que vayan analizando las pruebas de a poco y no se abrumen con todo en la terminal.
Puedes ejecutar las pruebas de cada grupo de objetivos de aprendizaje de manera individual con los siguientes comandos:
npm run test:oas-html
npm run test:oas-css
npm run test:oas-web-api
npm run test:oas-js
```
quiza en la parte de criterios de aceptacion ?

2023-08-24 23:58 UTC, unjust commented on README.md
> +  Este set nos proporciona la lista de los atletas que ganaron medallas en las olimpiadas de Río de Janeiro.
que fue el cambio aqui?

2023-08-24 23:58 UTC, unjust commented on README.md
> +- La aplicación debe permitir a la usuaria ver los items de la data en una visualización, que puede ser [tipo tarjetas](http://www.uxables.com/diseno-ux-ui/que-es-y-como-disenar-una-card/) o cualquie
```suggestion
- La aplicación debe permitir a la usuaria ver los items de la data en una visualización, que puede ser [tipo tarjetas](http://www.uxables.com/diseno-ux-ui/que-es-y-como-disenar-una-card/) o cualquier otra forma que tú decidas como la adecuada (pero desde aquí referimos a los items como "tarjetas"). **Cada una de las tarjetas deben estar contenidas en un elemento `<li>` y estos a su vez contenido en un elemento `<ul>`.**
```

2023-08-24 23:58 UTC, unjust commented on README.md
> +- La aplicación debe permitir a la usuaria filtrar la data. Deberás usar un elemento [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) con un atributo _id_ de valor `sele
```suggestion
- La aplicación debe permitir a la usuaria filtrar la data. Deberás usar un elemento [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) con un atributo _id_ de valor `select-filter` y un atributo _name_ con el nombre de la propiedad por la que filtrará (por ejemplo, si vas a filtrar por "type" el `<select>` tendrá  `name="type"`). Los `<option>` de este `<select>` deberán tener  tener en el atributo `value` el valor del filtro (por ejemplo, si vas a filtrar por type "fire" seria `<option value="fire">Fire</option>`). 
```

2023-08-25 00:12 UTC, unjust commented
si recuerdo en los crtierios de aceptacion deberia omitir "form" y agregar "footer"

2023-08-25 13:55 UTC, DeysiVergara commented on README.md
> +  Este set nos proporciona la lista de los atletas que ganaron medallas en las olimpiadas de Río de Janeiro.
la tilde en olimpiadas, nada más.

2023-08-25 17:19 UTC, unjust requested changes
aplicamos los correciones sugeridos y agregamos los partes de commando s de test y footer

2023-08-25 20:35 UTC, unjust approved these changes

2023-08-25 20:36 UTC, merged